FROM balenalib/raspberry-pi-debian:run-20210705

RUN mkdir -p /app/conf /app/bin

COPY ./chirpstack-concentratord-sx1301 /app/bin
COPY ./chirpstack-concentratord-sx1302 /app/bin

COPY ./*.toml /app/conf/
